### ISSUE TITLE
Stackoverflow exception

### ISSUE THREAD

**Issue by Tvede-dk** [csense-oss/idea-kotlin-checked-exceptions#17]
recursive variables causes this. 
stacktrack 
```
at csense.idea.base.bll.kotlin.KtPropertyKt.getGetterBody(KtProperty.kt:26)
	at csense.idea.base.bll.kotlin.KtPropertyKt.isGetterConstant(KtProperty.kt:20)
	at csense.idea.base.bll.kotlin.KtExpressionKt.isConstant(KtExpression.kt:17)
	at csense.idea.base.bll.kotlin.KtPropertyKt.isGetterConstant(KtProperty.kt:22)
	at csense.idea.base.bll.kotlin.KtExpressionKt.isConstant(KtExpression.kt:17)
	at csense.idea.base.bll.kotlin.KtPropertyKt.isGetterConstant(KtProperty.kt:22)
	at csense.idea.base.bll.kotlin.KtExpressionKt.isConstant(KtExpression.kt:17)
	at csense.idea.base.bll.kotlin.KtPropertyKt.isGetterConstant(KtProperty.kt:22)
	at csense.idea.base.bll.kotlin.KtExpressionKt.isConstant(KtExpression.kt:17)
	at csense.idea.base.bll.kotlin.KtPropertyKt.isGetterConstant(KtProperty.kt:22)
	at csense.idea.base.bll.kotlin.KtExpressionKt.isConstant(KtExpression.kt:17)

**Comment by Tvede-dk** [comment]
should be fixed in next version
