### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.idea.stubindex.KotlinFullClassNameIndex org.jetbrains.kotlin.idea.stubindex.KotlinFullClassNameIndex.getInstance()'

### ISSUE THREAD

**Issue by danny-su** [csense-oss/idea-kotlin-checked-exceptions#37]
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.idea.stubindex.KotlinFullClassNameIndex org.jetbrains.kotlin.idea.stubindex.KotlinFullClassNameIndex.getInstance()'
	at csense.idea.base.bll.psiWrapper.class.operations.ResolveKt.resolveByKotlin(Resolve.kt:32)
	at csense.idea.kotlin.checked.exceptions.builtin.operations.KotlinThrowingFunctionsKt.builtInThrowsTypes(KotlinThrowingFunctions.kt:24)
	at csense.idea.kotlin.checked.exceptions.builtin.operations.KotlinThrowingFunctionsKt.throwsTypesOrBuiltIn(KotlinThrowingFunctions.kt:12)
	at csense.idea.kotlin.checked.exceptions.bll.KtPsiFunctionKt.throwsTypesForSettings(KtPsiFunction.kt:13)
	at csense.idea.kotlin.checked.exceptions.bll.KtCallExpressionKt.throwsTypesForSettings(KtCallExpression.kt:9)
	at csense.idea.kotlin.checked.exceptions.lineMarkers.CheckedExceptionLineMarkerProvider.onCallExpression(CheckedExceptionLineMarkerProvider.kt:80)
	at csense.idea.kotlin.checked.exceptions.lineMarkers.CheckedExceptionLineMarkerProvider.tryParentsAsCallExpression(CheckedExceptionLineMarkerProvider.kt:71)
	at csense.idea.kotlin.checked.exceptions.lineMarkers.CheckedExceptionLineMarkerProvider.onCollectNavigationMarkers(CheckedExceptionLineMarkerProvider.kt:33)
	at csense.idea.base.bll.linemarkers.SafeRelatedItemLineMarkerProvider.collectNavigationMarkers(SafeRelatedItemLineMarkerProvider.kt:19)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:35)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:27)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:222)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:108)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:97)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

**Comment by Tvede-dk** [comment]
should be fixed in 2.2.0
