### ISSUE TITLE
java.lang.IllegalStateException: KotlinCacheService should not be used for the K2 mode.

### ISSUE THREAD

**Issue by danny-su** [csense-oss/idea-kotlin-checked-exceptions#41]
java.lang.IllegalStateException: KotlinCacheService should not be used for the K2 mode. See https://kotl.in/analysis-api/ for the migration.
	at org.jetbrains.kotlin.caches.resolve.KotlinCacheService$Companion.getInstance(KotlinCacheService.kt:24)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.getResolutionFacade(ResolutionUtils.kt:31)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.analyze(ResolutionUtils.kt:122)
	at csense.idea.base.bll.kotlin.KtExpressionKt.resolveExpressionType$default(KtExpression.kt:66)
	at csense.idea.base.bll.kotlin.KtThrowExpressionKt.tryResolveViaExpressionType(KtThrowExpression.kt:20)
	at csense.idea.base.bll.kotlin.KtThrowExpressionKt.resolveThrownTypeOrNull(KtThrowExpression.kt:12)
	at csense.idea.kotlin.checked.exceptions.visitors.IncrementalExceptionCheckerVisitor.visitThrowExpression(IncrementalExceptionCheckerVisitor.kt:151)
	at csense.idea.kotlin.checked.exceptions.visitors.IncrementalExceptionCheckerVisitor.visitThrowExpression(IncrementalExceptionCheckerVisitor.kt:19)
	at org.jetbrains.kotlin.psi.KtThrowExpression.accept(KtThrowExpression.java:30)
	at org.jetbrains.kotlin.psi.KtPsiUtil.visitChildren(KtPsiUtil.java:50)
	at org.jetbrains.kotlin.psi.KtBlockExpression.acceptChildren(KtBlockExpression.java:73)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:24)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:196)
	at org.jetbrains.kotlin.psi.KtVisitor.visitBlockExpression(KtVisitor.java:328)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:78)
	at org.jetbrains.kotlin.psi.KtPsiUtil.visitChildren(KtPsiUtil.java:50)
	at org.jetbrains.kotlin.psi.KtElementImpl.acceptChildren(KtElementImpl.java:72)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:24)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitCatchSection(KtVisitor.java:332)
	at org.jetbrains.kotlin.psi.KtCatchClause.accept(KtCatchClause.java:33)
	at org.jetbrains.kotlin.psi.KtPsiUtil.visitChildren(KtPsiUtil.java:50)
	at org.jetbrains.kotlin.psi.KtElementImpl.acceptChildren(KtElementImpl.java:72)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:24)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:196)
	at org.jetbrains.kotlin.psi.KtVisitor.visitTryExpression(KtVisitor.java:268)
	at csense.idea.kotlin.checked.exceptions.visitors.IncrementalExceptionCheckerVisitor.visitTryExpression(IncrementalExceptionCheckerVisitor.kt:37)
	at csense.idea.kotlin.checked.exceptions.visitors.IncrementalExceptionCheckerVisitor.visitTryExpression(IncrementalExceptionCheckerVisitor.kt:19)
	at org.jetbrains.kotlin.psi.KtTryExpression.accept(KtTryExpression.java:35)
	at org.jetbrains.kotlin.psi.KtPsiUtil.visitChildren(KtPsiUtil.java:50)
	at org.jetbrains.kotlin.psi.KtBlockExpression.acceptChildren(KtBlockExpression.java:73)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:24)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:196)
	at org.jetbrains.kotlin.psi.KtVisitor.visitBlockExpression(KtVisitor.java:328)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:78)
	at org.jetbrains.kotlin.psi.KtElementImplStub.acceptChildren(KtElementImplStub.java:86)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:24)
	at org.jetbrains.kotlin.psi.KtTreeVisitor.visitKtElement(KtTreeVisitor.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:196)
	at org.jetbrains.kotlin.psi.KtVisitor.visitDeclaration(KtVisitor.java:29)
	at org.jetbrains.kotlin.psi.KtVisitor.visitNamedDeclaration(KtVisitor.java:416)
	at org.jetbrains.kotlin.psi.KtVisitor.visitNamedFunction(KtVisitor.java:53)
	at csense.idea.kotlin.checked.exceptions.visitors.IncrementalExceptionCheckerVisitor.visitNamedFunction(IncrementalExceptionCheckerVisitor.kt:123)
	at csense.idea.kotlin.checked.exceptions.visitors.IncrementalExceptionCheckerVisitor.visitNamedFunction(IncrementalExceptionCheckerVisitor.kt:19)
	at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:39)
	at csense.idea.kotlin.checked.exceptions.inspections.IncrementalCheckedExceptionInspection.buildVisitor$lambda$0(IncrementalCheckedExceptionInspection.kt:46)
	at csense.idea.base.visitors.NamedFunctionOrCustomPropertyCodeVisitor.visitNamedFunction(NamedFunctionOrCustomPropertyCodeVisitor.kt:15)
	at csense.idea.kotlin.checked.exceptions.inspections.SettingsBasedNamedFunctionOrCustomPropertyCodeVisitor.visitNamedFunction(IncrementalCheckedExceptionInspection.kt:73)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:491)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:39)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner$InspectionProblemHolder.visitElement(InspectionRunner.java:577)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processContext$18(InspectionRunner.java:404)
	at com.intellij.codeInsight.daemon.impl.InspectionVisitorOptimizer.acceptElements(InspectionVisitorOptimizer.java:210)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processContext(InspectionRunner.java:402)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$7(InspectionRunner.java:178)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:333)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$executeInImpatientReadAction$15(InspectionRunner.java:383)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:158)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:150)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$executeInImpatientReadAction$16(InspectionRunner.java:374)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.executeInImpatientReadAction(InspectionRunner.java:374)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$8(InspectionRunner.java:171)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:126)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:207)
	at com.intellij.concurrency.ApplierCompleter.helpOthers(ApplierCompleter.java:227)
	at com.intellij.concurrency.ApplierCompleter.helpAll(ApplierCompleter.java:186)
	at com.intellij.concurrency.ApplierCompleter.lambda$exec$0(ApplierCompleter.java:116)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:158)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:169)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:150)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:544)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:176)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:150)
	at com.intellij.concurrency.ApplierCompleter.exec(ApplierCompleter.java:118)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

**Comment by Tvede-dk** [comment]
I will release a version 3.0.0 soon. It will fix this for now, but I suspect that most of the code should actually be written to use the analysis api, which unfortunately is not a simple thing :(
It should work, I have tested with both the "lowest" allowed version (243, since K2 mode requires that as the minimum, kinda sad with regards to backward compatibility) and the most up to date EAP. (also android studio is of cause tried out). 
In  both k1 & k2 mode.
If nothing comes up it should be out in a couple of days :)
